# Generated by Django 5.1.7 on 2025-05-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_artikel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
